spring.opcua.server:
  product-uri: urn:signencrypt:opcua
  application-name: Sign & Encrypt Auth OPC UA Server
  https.enabled: true
  authentication.token-policies: username
  security:
    policy: Basic256Sha256
    mode: SignAndEncrypt